[env:arduino_nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
lib_ignore =
    Emulator

[env:emulator]
platform = native
build_flags =
    -D EMULATOR
extra_scripts =
    pre:build_scripts/emulator_deps.py