[env:arduino_nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
lib_ignore =
    Emulator
    imgui
    glad

[env:emulator]
platform = native
build_flags =
    -D EMULATOR
    -D IMGUI_IMPL_OPENGL_LOADER_GLAD
extra_scripts =
    pre:build_scripts/emulator_deps.py